---
image: python:3.7-alpine3.10

cache:
  key: "$CI_JOB_NAME-$CI_COMMIT_REF_SLUG"

before_script:
  # get terraform ready
  - apk add terraform
  - terraform --version
  - terraform init
  # install ansible
  - apk add ansible
  - ansible --version
  - apk add ansible-lint
  - ansible-lint --version
  # install python tools
  - pip install -r requirements.txt


stages:
  - validate
  - lint
  - test
  - plan


python:
  stage: validate
  script:
    - python -m py_compile src/*.py
  stage: lint
  script:
    - flake8 src/*.py
  only:
    - branches


ansible:
  stage: validate
  script:
    ansible-playbook --syntax-check infrastructure/playbooks/*.yml
  stage: lint
  script:
    - ansible-lint infrastructure/playbooks/*
  only:
    - branches


terraform:
  stage: validate
  script:
    - terraform validate
  stage: lint
  script:
    - terraform fmt -recursive -check infrastructure/
  only:
    - branches
