---
image: python:3.7-alpine3.10

cache:
  key: "$CI_JOB_NAME-$CI_COMMIT_REF_SLUG"

before_script:
  # get terraform ready
  - apk add terraform
  - terraform --version
  - terraform init
  # install ansible
  - apk add ansible
  - ansible-playbook --version
  - apk add ansible-lint
  - ansible-lint --version
  # install python tools
  - pip install -r requirements.txt


stages:
  - accept
  - build
  - test
  - plan
  - apply

## accept jobs focus on syntax and linting
accept 1/3:
  # python
  stage: accept
  script:
    - python -m py_compile src/*.py
    - flake8 src/
    - flake8 test/
  only:
    - branches

accept 2/3:
  # ansible
  stage: accept
  script:
    - ansible-playbook --syntax-check infrastructure/playbooks/*.yml
    - ansible-lint infrastructure/playbooks/*
  only:
    - branches

accept 3/3:
  # terraform
  stage: accept
  script:
    - terraform validate
    - terraform fmt -recursive -check infrastructure/
  only:
    - branches

python test:
  stage: test
  script:
    - pytest
  only:
    - branches
