---
- hosts: all
  name: Install and Configure Wireguard Relay Server
  remote_user: ubuntu
  vars:
    ansible_python_interpreter: /usr/bin/python3

  tasks:
  - name: Install latest version of Wireguard
    apt:
      name: wireguard
      state: present
      update_cache: true
    become: true

  - name: Upload wg configuration files
    become: true
    copy:
      src: wg0.conf
      dest: /etc/wireguard/wg0.conf

      #  - name: wg0 up
      #become: true
      #raw: wg-quick up wg0
      #changed_when: false
